[project]
name = "model-development"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.14.0",
    "numpy>=2.2.6",
    "pillow>=11.3.0",
    "tensorflow>=2.20.0",
]
